### ISSUE TITLE
Importing the HoloToolkit-Unity doesn't bring the "HoloToolkit" menu item

### ISSUE THREAD

**Issue by JeanValjean17** [cmusatyalab/gabriel-instruction#30]
Hello,

When I'm following the steps for building the hololens client, adding the HololensToolkit package doesn't add the HoloToolkit menu item. 

Also, when I open the Unity Project of the Hololens clients these errors appear in the Unity console:

![image](https://user-images.githubusercontent.com/7123514/73445939-22e97980-435c-11ea-84da-d92c7df0df90.png)

Even though I solve these errors in the Visual Studio project they keep appearing in the Unity Console. Is this related to the HoloToolkit menu item not appearing in the project?

I'm using Unity HoloLens 5.4.0f3-HTP and VS 2015 as described in the readme.

Regards,

Jean

**Comment by rogerthat94** [comment]
Hi Jean,

If you delete the following lines:
```
using System.Collections.Concurrent;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;
```
from `hololens-client/Assets/Scripts/GuidanceControl.cs` and comment out the parts of this file that use these imports, does it fix the the problem?

**Comment by JeanValjean17** [comment]
Hi Roger,

Thanks for replying :)

I did it and the Menu Item appeared, but then when I build the Visual Studio Solution new errors appear:

![image](https://user-images.githubusercontent.com/7123514/74331283-a317d200-4d93-11ea-9343-0e9d49d1ceaa.png)

If I don't comment the lines related to `using System.Collections.Concurrent;` then it will complain about them too...

Also, these Instruction and Gabriel Classes shown in the error are in this folder:
`...\gabriel-instruction-master\hololens-client\UWP\Assembly-CSharp\Scripts`

Do they need to be included somehow to the visual studio project, or how does it work? I took a look inside them and they are using `Google.Protobuf`

**Comment by rogerthat94** [comment]
No problem! 

Could you try building [this](https://github.com/cmusatyalab/gabriel-instruction/tree/master/hololens-client) version of the Hololens Client? This is a snapshot of the code before I modified Gabriel to transmit data using Protocol Buffers and WebSockets. If you get this working first, I can help you modify it to use my latest code. 

Note that you will have to [add HoloToolkit](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/82fc64462b987f1d572d0db9bb3b39fe8f1a56f0/GettingStarted.md#using-holotoolkit-unity-in-your-project) to the Unity project after you clone this version of the repository. 

Note also that we only have holograms to go along with Gabriel-Sandwich. The client might work with our other instruction-based Gabriel applications. But it won't show any holograms. The sandwich application requires [this](https://wujus.com/small-world-toys-living-sandwich-21310004w156/) specific toy set. But you are certainly welcome to modify the client or the sandwich server yourself.

**Comment by JeanValjean17** [comment]
The version you linked seems to be the same that has the Protocol Buffers, should I check a specific commit?

**Comment by rogerthat94** [comment]
Sorry, I meant to link to this https://github.com/cmusatyalab/gabriel-instruction/tree/old-hololens/hololens-client

**Comment by JeanValjean17** [comment]
Thanks, I tried this one and I was able to build and run it on the device with no problems. What would be needed to make it work with the Protocol Buffers?

Oh, regarding the holograms, for now, I only intend to work with the Gabriel-Sandwich for which we already have that kit you specified :)

**Comment by rogerthat94** [comment]
Open the solution that you build from Unity with Visual Studio Community 2015. You will make modifications to files in Visual Studio that will prevent the project from building in Unity. But you can just build everything with Visual Studio going forward. 

Update the contents of [GuidanceControl.cs](https://github.com/cmusatyalab/gabriel-instruction/blob/master/hololens-client/Assets/Scripts/GuidanceControl.cs) and [Const.cs](https://github.com/cmusatyalab/gabriel-instruction/blob/master/hololens-client/Assets/Scripts/Const.cs). Then delete all text in the files MyLogger.cs and TokenController.cs. But don't delete these files. Just keep them on disk with no content in them. 

Would you mind sharing the additional steps that you took to get the version that I linked to build? I have not gotten that working myself but would like to be able to.

**Comment by JeanValjean17** [comment]
Do you mean to update them with the contents of the master branch, right? 

For the building, I didn't take any additional steps I just followed the normal steps and it built correctly.

**Comment by rogerthat94** [comment]
That's correct. 

That's interesting. Unity gave me errors when I tried on a different computer. Glad it worked for you though!

**Comment by JeanValjean17** [comment]
It worked now, tried with the server as well and works properly. Thanks for your help Roger!

**Comment by rogerthat94** [comment]
No problem! Glad to hear you got it working.
